version: '3.8'

services:
  # Servicio de persistencia (Base de Datos)
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: usuario_uisek
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: mensajes_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Servicio Backend (Node.js)
  app:
    build: ./backend
    container_name: node_backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: usuario_uisek
      DB_PASSWORD: password123
      DB_NAME: mensajes_db
    depends_on:
      - db

volumes:
  postgres_data: